- ros_topic_name: /shoulder_yaw_cmd
  gz_topic_name: /model/rover/joint/shoulder_yaw/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /shoulder_pitch_cmd
  gz_topic_name: /model/rover/joint/shoulder_pitch/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /elbow_pitch_cmd
  gz_topic_name: /model/rover/joint/elbow_pitch/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /elbow_roll_cmd
  gz_topic_name: /model/rover/joint/elbow_roll/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /wrist_pitch_cmd
  gz_topic_name: /model/rover/joint/wrist_pitch/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ
- ros_topic_name: /wrist_roll_cmd
  gz_topic_name: /model/rover/joint/wrist_roll/0/cmd_pos
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: gz.msgs.Double
  direction: ROS_TO_GZ